import type { Bookmaker } from "./bookmakers";
import type { Market } from "./markets";

export const selectionMappings: Partial<
  Record<Market, Record<Bookmaker, Record<string, string>>>
> = {
  MATCH_RESULT: {
    sportybet: {
      Home: "HOME_WIN",
      "1": "HOME_WIN",
      Draw: "DRAW",
      X: "DRAW",
      Away: "AWAY_WIN",
      "2": "AWAY_WIN",
    },
    bet9ja: {
      "1": "HOME_WIN",
      X: "DRAW",
      "2": "AWAY_WIN",
      Home: "HOME_WIN",
      Draw: "DRAW",
      Away: "AWAY_WIN",
    },
    onexbet: {
      "1": "HOME_WIN",
      X: "DRAW",
      "2": "AWAY_WIN",
      Home: "HOME_WIN",
      Draw: "DRAW",
      Away: "AWAY_WIN",
    },
  },

  DOUBLE_CHANCE: {
    sportybet: {
      "1X": "HOME_OR_DRAW",
      "12": "HOME_OR_AWAY",
      X2: "DRAW_OR_AWAY",
    },
    bet9ja: {
      "1X": "HOME_OR_DRAW",
      "12": "HOME_OR_AWAY",
      X2: "DRAW_OR_AWAY",
    },
    onexbet: {
      "1X": "HOME_OR_DRAW",
      "12": "HOME_OR_AWAY",
      X2: "DRAW_OR_AWAY",
    },
  },

  BOTH_TEAMS_TO_SCORE: {
    sportybet: {
      Yes: "BTTS_YES",
      No: "BTTS_NO",
    },
    bet9ja: {
      GG: "BTTS_YES",
      NG: "BTTS_NO",
      Yes: "BTTS_YES",
      No: "BTTS_NO",
    },
    onexbet: {
      Yes: "BTTS_YES",
      No: "BTTS_NO",
    },
  },

  DRAW_NO_BET: {
    sportybet: {
      Home: "DNB_HOME",
      Away: "DNB_AWAY",
      "1": "DNB_HOME",
      "2": "DNB_AWAY",
    },
    bet9ja: {
      Home: "DNB_HOME",
      Away: "DNB_AWAY",
      "1": "DNB_HOME",
      "2": "DNB_AWAY",
    },
    onexbet: {
      Home: "DNB_HOME",
      Away: "DNB_AWAY",
      "1": "DNB_HOME",
      "2": "DNB_AWAY",
    },
  },

  FIRST_HALF_RESULT: {
    sportybet: {
      Home: "FH_HOME_WIN",
      "1": "FH_HOME_WIN",
      Draw: "FH_DRAW",
      X: "FH_DRAW",
      Away: "FH_AWAY_WIN",
      "2": "FH_AWAY_WIN",
    },
    bet9ja: {
      "1": "FH_HOME_WIN",
      X: "FH_DRAW",
      "2": "FH_AWAY_WIN",
      Home: "FH_HOME_WIN",
      Draw: "FH_DRAW",
      Away: "FH_AWAY_WIN",
    },
    onexbet: {
      "1": "FH_HOME_WIN",
      X: "FH_DRAW",
      "2": "FH_AWAY_WIN",
      Home: "FH_HOME_WIN",
      Draw: "FH_DRAW",
      Away: "FH_AWAY_WIN",
    },
  },

  OVER_UNDER: {
    sportybet: {
      Over: "OVER",
      Under: "UNDER",
      "Over 0.5": "OVER_0_5",
      "Under 0.5": "UNDER_0_5",
      "Over 1.5": "OVER_1_5",
      "Under 1.5": "UNDER_1_5",
      "Over 2.5": "OVER_2_5",
      "Under 2.5": "UNDER_2_5",
      "Over 3.5": "OVER_3_5",
      "Under 3.5": "UNDER_3_5",
    },
    bet9ja: {
      Over: "OVER",
      Under: "UNDER",
      "Over 0.5": "OVER_0_5",
      "Under 0.5": "UNDER_0_5",
      "Over 1.5": "OVER_1_5",
      "Under 1.5": "UNDER_1_5",
      "Over 2.5": "OVER_2_5",
      "Under 2.5": "UNDER_2_5",
      "Over 3.5": "OVER_3_5",
      "Under 3.5": "UNDER_3_5",
    },
    onexbet: {
      Over: "OVER",
      Under: "UNDER",
      "Over 0.5": "OVER_0_5",
      "Under 0.5": "UNDER_0_5",
      "Over 1.5": "OVER_1_5",
      "Under 1.5": "UNDER_1_5",
      "Over 2.5": "OVER_2_5",
      "Under 2.5": "UNDER_2_5",
      "Over 3.5": "OVER_3_5",
      "Under 3.5": "UNDER_3_5",
    },
  },
};

export const reverseSelectionLabels: Record<Bookmaker, Record<string, string>> = {
  sportybet: {
    HOME_WIN: "Home",
    DRAW: "Draw",
    AWAY_WIN: "Away",
    HOME_OR_DRAW: "1X",
    HOME_OR_AWAY: "12",
    DRAW_OR_AWAY: "X2",
    BTTS_YES: "Yes",
    BTTS_NO: "No",
    DNB_HOME: "Home",
    DNB_AWAY: "Away",
    FH_HOME_WIN: "Home",
    FH_DRAW: "Draw",
    FH_AWAY_WIN: "Away",
    OVER: "Over",
    UNDER: "Under",
    OVER_0_5: "Over 0.5",
    UNDER_0_5: "Under 0.5",
    OVER_1_5: "Over 1.5",
    UNDER_1_5: "Under 1.5",
    OVER_2_5: "Over 2.5",
    UNDER_2_5: "Under 2.5",
    OVER_3_5: "Over 3.5",
    UNDER_3_5: "Under 3.5",
  },

  bet9ja: {
    HOME_WIN: "1",
    DRAW: "X",
    AWAY_WIN: "2",
    HOME_OR_DRAW: "1X",
    HOME_OR_AWAY: "12",
    DRAW_OR_AWAY: "X2",
    BTTS_YES: "GG",
    BTTS_NO: "NG",
    DNB_HOME: "1",
    DNB_AWAY: "2",
    FH_HOME_WIN: "1",
    FH_DRAW: "X",
    FH_AWAY_WIN: "2",
    OVER: "Over",
    UNDER: "Under",
    OVER_0_5: "Over 0.5",
    UNDER_0_5: "Under 0.5",
    OVER_1_5: "Over 1.5",
    UNDER_1_5: "Under 1.5",
    OVER_2_5: "Over 2.5",
    UNDER_2_5: "Under 2.5",
    OVER_3_5: "Over 3.5",
    UNDER_3_5: "Under 3.5",
  },

  onexbet: {
    HOME_WIN: "1",
    DRAW: "X",
    AWAY_WIN: "2",
    HOME_OR_DRAW: "1X",
    HOME_OR_AWAY: "12",
    DRAW_OR_AWAY: "X2",
    BTTS_YES: "Yes",
    BTTS_NO: "No",
    DNB_HOME: "1",
    DNB_AWAY: "2",
    FH_HOME_WIN: "1",
    FH_DRAW: "X",
    FH_AWAY_WIN: "2",
    OVER: "Over",
    UNDER: "Under",
    OVER_0_5: "Over 0.5",
    UNDER_0_5: "Under 0.5",
    OVER_1_5: "Over 1.5",
    UNDER_1_5: "Under 1.5",
    OVER_2_5: "Over 2.5",
    UNDER_2_5: "Under 2.5",
    OVER_3_5: "Over 3.5",
    UNDER_3_5: "Under 3.5",
  },
};